# Generated by Django 5.1.7 on 2025-04-21 09:33

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpecCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_color_variant', models.BooleanField(default=False)),
                ('overview', wagtail.fields.StreamField([('paragraph', 0), ('h4', 1), ('h6', 2), ('ordered_list', 3), ('unordered_list', 4), ('blockquote_1', 5), ('image', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['p', 'a']}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['h4']}), 2: ('wagtail.blocks.CharBlock', (), {'features': ['h6']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['ol']}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul']}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '800 x 600', 'label': 'Image'})}, null=True)),
                ('youtube_embed', models.TextField(blank=True, null=True)),
                ('image_dimension', models.ImageField(blank=True, null=True, upload_to='product/dimension')),
                ('pdf_catalogue', models.FileField(blank=True, null=True, upload_to='products/pdf_catalogues')),
                ('highlight_battery', models.CharField(blank=True, max_length=255, null=True)),
                ('highlight_seat', models.CharField(blank=True, max_length=255, null=True)),
                ('highlight_range', models.CharField(blank=True, max_length=255, null=True)),
                ('highlight_power', models.CharField(blank=True, max_length=255, null=True)),
                ('highlight_acceleration', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CarSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('carspec_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_specs_category', to='product.carspeccategory')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCarSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('carspec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_car_specs', to='product.carspec')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_car_specs', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('color_hex', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='products/color_variants')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_variants', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='product.product')),
            ],
        ),
    ]
