# Generated by Django 5.1.7 on 2025-04-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
