# Generated by Django 5.1.7 on 2025-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_trans',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery'),
        ),
    ]
