# Generated by Django 5.1.7 on 2025-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
