# Generated by Django 5.1.7 on 2025-05-04 04:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
                ('enable_social_link', models.BooleanField(default=False)),
                ('enable_floating_whatsapp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Link Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('option', 'Option'), ('link', 'Link'), ('image', 'Image')], default='link', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='link_items/images')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_items', to='home.linkpage')),
            ],
            options={
                'verbose_name': 'Link Item',
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
