# Generated by Django 5.1.7 on 2025-05-05 14:09

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_linkpage_linkitem_delete_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkitem',
            name='text_content',
            field=wagtail.fields.StreamField([('paragraph', 0), ('h4', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['p', 'a']}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['h4']})}, null=True),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='background_color',
            field=models.CharField(default='f2f2f2', max_length=6),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='meta_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='meta_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='primary_color',
            field=models.CharField(default='0f0f0f', max_length=6),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='secondary_color',
            field=models.CharField(default='0f0f0f', max_length=6),
        ),
        migrations.AlterField(
            model_name='linkitem',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('text_content', 'Text Content')], default='link', max_length=20),
        ),
    ]
