# Generated by Django 5.1.7 on 2025-05-09 10:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_linkpage_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpage',
            name='background_color',
            field=colorfield.fields.ColorField(default='#f2f2f2', image_field=None, max_length=6, samples=None),
        ),
        migrations.AlterField(
            model_name='linkpage',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0f0f0f', image_field=None, max_length=6, samples=None),
        ),
        migrations.AlterField(
            model_name='linkpage',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#0f0f0f', image_field=None, max_length=6, samples=None),
        ),
    ]
