# Generated by Django 5.1.7 on 2025-04-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light')], default='DARK', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('cta_button', models.BooleanField(default=True)),
                ('cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_link', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='slider_images')),
            ],
        ),
    ]
