# Generated by Django 5.1.7 on 2025-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='cta_blank',
            field=models.BooleanField(default=False),
        ),
    ]
