# Generated by Django 5.1.7 on 2025-04-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_slider_cta_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('cta_text', models.CharField(max_length=60)),
                ('cta_link', models.URLField(max_length=255)),
                ('cta_blank', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='link_banners')),
            ],
        ),
    ]
