# Generated by Django 5.1.7 on 2025-04-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_linkbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_page_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('footer_description', models.CharField(blank=True, max_length=140, null=True)),
                ('bottom_cta_1_title', models.CharField(blank=True, max_length=40, null=True)),
                ('bottom_cta_1_image', models.ImageField(blank=True, null=True, upload_to='cta/')),
                ('bottom_cta_1_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('bottom_cta_1_button_text', models.CharField(blank=True, max_length=20, null=True)),
                ('bottom_cta_1_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('bottom_cta_1_button_link', models.URLField(blank=True, null=True)),
                ('bottom_cta_1_new_tab', models.BooleanField(default=False)),
                ('bottom_cta_2_title', models.CharField(blank=True, max_length=40, null=True)),
                ('bottom_cta_2_image', models.ImageField(blank=True, null=True, upload_to='cta/')),
                ('bottom_cta_2_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('bottom_cta_2_button_text', models.CharField(blank=True, max_length=20, null=True)),
                ('bottom_cta_2_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('bottom_cta_2_button_link', models.URLField(blank=True, null=True)),
                ('bottom_cta_2_new_tab', models.BooleanField(default=False)),
                ('product_highlight_image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('product_highlight_title_1', models.CharField(blank=True, max_length=20, null=True)),
                ('product_highlight_title_2', models.CharField(blank=True, max_length=20, null=True)),
                ('product_highlight_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('product_detail_image', models.ImageField(blank=True, null=True, upload_to='details/')),
                ('product_detail_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('product_detail_button_text', models.CharField(blank=True, max_length=20, null=True)),
                ('product_detail_button_link', models.URLField(blank=True, null=True)),
                ('product_detail_new_tab', models.BooleanField(default=False)),
                ('product_detail_icon_1', models.CharField(blank=True, max_length=20, null=True)),
                ('product_detail_desc_1', models.CharField(blank=True, max_length=80, null=True)),
                ('product_detail_icon_2', models.CharField(blank=True, max_length=20, null=True)),
                ('product_detail_desc_2', models.CharField(blank=True, max_length=80, null=True)),
                ('product_detail_icon_3', models.CharField(blank=True, max_length=20, null=True)),
                ('product_detail_desc_3', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
