# Generated by Django 5.1.7 on 2025-04-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_brandingsetting_contentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsetting',
            name='product_detail_title_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contentsetting',
            name='product_detail_title_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contentsetting',
            name='product_detail_title_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
