# Generated by Django 5.1.7 on 2025-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contentsetting_product_detail_title_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsetting',
            name='product_detail_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
