# Generated by Django 5.1.7 on 2025-05-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_contentsetting_product_detail_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandingsetting',
            options={'verbose_name': 'Branding Setting'},
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='company_name',
            field=models.CharField(default='Denza Indonesia', max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/favicon/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='brandingsetting',
            name='site_name',
            field=models.CharField(default='Denza', max_length=255, verbose_name='Site Name'),
        ),
    ]
